In [1]:
import numpy as np

import torch
from torch import nn
from torchvision import datasets
from torch.utils.data import DataLoader

# creating tensors


In [2]:
# 1. from direct data

data = [[1,2],[3,4]]
data_x = torch.tensor(data)

In [3]:
# from numoy arrays

np_array = np.array(data)
x_data = torch.from_numpy(np_array)

In [5]:
# from another tensor

x_ones = torch.ones_like(data_x) #retains properties of data_x
print(f"ones tensor : \n {x_ones} \n")

x_rand = torch.rand_like(data_x, dtype=torch.float) # overrrides data type
print(f"rand tensor : \n {x_rand}")

ones tensor : 
 tensor([[1, 1],
        [1, 1]]) 

rand tensor : 
 tensor([[0.3168, 0.7700],
        [0.1294, 0.3461]])


## with random or constant values

In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand tensor \n {rand_tensor} \n")
print(f"ones tensor \n {ones_tensor} \n")
print(f"zeros tensor \n {zeros_tensor}")

rand tensor 
 tensor([[0.3909, 0.3268, 0.8572],
        [0.3474, 0.4375, 0.1078]]) 

ones tensor 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros tensor 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## attributes of  tensor
* shape
* dtype
* device

In [7]:
tensor = torch.rand(3,4)

print(f"shape {tensor.shape}\n")
print(f"dtype {tensor.dtype}\n")
print(f"device {tensor.device}")

shape torch.Size([3, 4])

dtype torch.float32

device cpu


## operations on tensors
*  arithmetic
* linear algebra
* martrix manipulation (transposing, indexing, slicing)


In [8]:
# if torch.cuda.is_available:
#     tensor = tensor.to("cuda")
    
tensor = torch.rand(4,4)
print(f"tensor \n{tensor}")

print(f"first row\n {tensor[0]}")
print(f"first column\n {tensor[:,0]}")
print(f"last row\n {tensor[...,-1]}")

tensor 
tensor([[0.4740, 0.9584, 0.1184, 0.0952],
        [0.3935, 0.2818, 0.5465, 0.0479],
        [0.4739, 0.3570, 0.5758, 0.7113],
        [0.8996, 0.4549, 0.4133, 0.2065]])
first row
 tensor([0.4740, 0.9584, 0.1184, 0.0952])
first column
 tensor([0.4740, 0.3935, 0.4739, 0.8996])
last row
 tensor([0.0952, 0.0479, 0.7113, 0.2065])


### joining tensors

In [10]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)# dim = 1 : columnwise, 0 : rowise
print(t1)

tensor([[0.4740, 0.9584, 0.1184, 0.0952, 0.4740, 0.9584, 0.1184, 0.0952, 0.4740,
         0.9584, 0.1184, 0.0952],
        [0.3935, 0.2818, 0.5465, 0.0479, 0.3935, 0.2818, 0.5465, 0.0479, 0.3935,
         0.2818, 0.5465, 0.0479],
        [0.4739, 0.3570, 0.5758, 0.7113, 0.4739, 0.3570, 0.5758, 0.7113, 0.4739,
         0.3570, 0.5758, 0.7113],
        [0.8996, 0.4549, 0.4133, 0.2065, 0.8996, 0.4549, 0.4133, 0.2065, 0.8996,
         0.4549, 0.4133, 0.2065]])


### arithmetic operations

In [34]:
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T, out=y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor*tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out=z3)

print(f"y1: {y1}\n y2 : {y2} \n y3 : {y3}\n z1 {z1}\n z2 {z2} \n z3: {z3}")

y1: tensor([[2.2597, 1.4412, 1.2105, 1.9873],
        [1.4412, 1.0974, 0.8422, 1.3024],
        [1.2105, 0.8422, 1.0430, 1.0537],
        [1.9873, 1.3024, 1.0537, 1.8544]])
 y2 : tensor([[2.2597, 1.4412, 1.2105, 1.9873],
        [1.4412, 1.0974, 0.8422, 1.3024],
        [1.2105, 0.8422, 1.0430, 1.0537],
        [1.9873, 1.3024, 1.0537, 1.8544]]) 
 y3 : tensor([[2.2597, 1.4412, 1.2105, 1.9873],
        [1.4412, 1.0974, 0.8422, 1.3024],
        [1.2105, 0.8422, 1.0430, 1.0537],
        [1.9873, 1.3024, 1.0537, 1.8544]])
 z1 tensor([[0.5652, 0.8324, 0.3226, 0.5396],
        [0.0397, 0.4941, 0.0459, 0.5177],
        [0.0748, 0.0126, 0.2622, 0.6934],
        [0.6106, 0.6058, 0.0493, 0.5886]])
 z2 tensor([[0.5652, 0.8324, 0.3226, 0.5396],
        [0.0397, 0.4941, 0.0459, 0.5177],
        [0.0748, 0.0126, 0.2622, 0.6934],
        [0.6106, 0.6058, 0.0493, 0.5886]]) 
 z3: tensor([[0.5652, 0.8324, 0.3226, 0.5396],
        [0.0397, 0.4941, 0.0459, 0.5177],
        [0.0748, 0.0126, 0.2622, 0.6934]

#### single element tensor

In [38]:
agg = tensor.sum()
agg_item = agg.item()

print("agg", agg)
print("agg item", agg_item)
print("agg item type",type(agg_item))

agg tensor(9.0820)
agg item 9.081981658935547
agg item type <class 'float'>


#### inplace operations
* operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x

In [42]:
print(tensor)

tensor.add_(10)
print(tensor)

tensor([[10.7518, 10.9124, 10.5679, 10.7345],
        [10.1992, 10.7029, 10.2142, 10.7195],
        [10.2734, 10.1123, 10.5120, 10.8327],
        [10.7814, 10.7784, 10.2220, 10.7672]])
tensor([[20.7518, 20.9124, 20.5679, 20.7345],
        [20.1992, 20.7029, 20.2142, 20.7195],
        [20.2734, 20.1123, 20.5120, 20.8327],
        [20.7814, 20.7784, 20.2220, 20.7672]])


#### bridge with numpy

In [44]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [45]:
# a change in tensor reflects in numpy array
t.add_(10)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([11., 11., 11., 11., 11.])
n : [11. 11. 11. 11. 11.]


In [47]:
# numpy  array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [48]:
# change in numpy array reflects in tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
